<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Contact Form Submissions</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .submission {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 20px;
            background-color: #fff;
        }
        .submission-header {
            border-bottom: 1px solid #eee;
            padding-bottom: 10px;
            margin-bottom: 15px;
        }
        .submission-meta {
            color: #666;
            font-size: 0.9em;
            margin-bottom: 10px;
        }
        .message-content {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-top: 10px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            color: #666;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>New Contact Form Submissions</h1>
        <p>You have {{ $count }} new contact form {{ $count === 1 ? 'submission' : 'submissions' }} from your website.</p>
    </div>

    @foreach($submissions as $submission)
        <div class="submission">
            <div class="submission-header">
                <h2>{{ $submission->full_name }}</h2>
                <div class="submission-meta">
                    <strong>Email:</strong> {{ $submission->email }}<br>
                    <strong>Submitted:</strong> {{ $submission->created_at->format('M j, Y g:i A') }}<br>
                    <strong>Page:</strong> {{ $submission->page_submitted }}<br>
                    <strong>IP Address:</strong> {{ $submission->ip_address }}
                </div>
            </div>

            <div>
                <strong>Message:</strong>
                <div class="message-content">
                    {!! nl2br(e($submission->message)) !!}
                </div>
            </div>
        </div>
    @endforeach

    <div class="footer">
        <p>
            This email was automatically generated by your website's contact form system.<br>
            To manage these submissions, visit your admin dashboard.
        </p>
    </div>
</body>
</html>
