@extends('pages.blogs.backgrounds.blogs')

@section('blog-content')
    <div class="py-4">
        <p class="mb-0">The student experience was always central to the mission of Greenhouse Studios, a mindset which has only strengthened since the unit merged with the Internal Insights & Innovation team in September 2025. This blog post unpacks the concept of “The Treehouse” – the mechanism forged for the weekly coming-together of the talented collective of student employees who made Greenhouse Studios tick. (Spoiler alert: this mindset is still at the forefront of our work in our newly merged department!) .</p>
    </div>

    <div class="py-4">
        <p class="mb-0">The Treehouse was comprised of graduate & undergraduate employees who hailed from a wide range of diverse backgrounds, and their primary charge was to bring their whole selves to the table in pursuit of experiencing a truly life-transformative educational experience during their tenure in the studio. While specific project work was often focused on promoting the image of Greenhouse Studios, the deeper purpose of The Treehouse was to facilitate a space where students could gain confidence in themselves while producing high-quality deliverables for their own portfolios. The name itself was generated by the students and resonated with us as it perfectly embodied the way we felt when we would gather. In The Treehouse, we were allowed a momentary escape from the stressors of our individual lives and encouraged to dream about the possibilities before us with childlike wonder.</p>
    </div>
    
    <div class="py-4">
        <p class="mb-0">We began the academic terms by establishing students' personal & professional goals, and then we aligned projects and teams with their intended trajectories. Though I led the group, it was important to me that this team was highly collaborative with a completely flat hierarchy. Therefore, we laid out all of the options on the table together and I (tried to) act more as a rudder than as a "boss." Everyone had an equal voice, from the first-year undergraduate interactive media major to the seventh-year humanities PhD candidate. </p>
    </div>


    <div class="py-4">
        <p class="mb-0">Students took on significant and ambitious projects, such as a complete redesign of the Greenhouse Studios website, a refresh of the studio's assets, robust social media campaigns, and successful fundraising efforts. </p>
    </div>

    <h2>Discovering Student Trajectories </h2>
    
    <div class="py-4 clearfix">
        @include('pages.blogs.components.blog-image', [
            'src' => 'storage/post_images/treehouse-img1-arden.png',
            'alt' => 'Arden Stull',
            'caption' => 'One of ten student features created by Lauren Harland (BA \'24) to welcome back students in the Fall 2022 semester. Arden Ricciardone returned to the studio in August for her sixth semester working with us and wrote about her ambitions for her senior year in a student-authored blog post.'
        ])
        <p class="mb-0">The key to the success of our students lies in understanding why they've come to work with us in the first place. Only then can we figure out how to give them the tools and opportunities they need to blossom. We spent the first few Treehouse meetings of each term just taking stock of where each individual has been, where they were in that moment, and where thought they might want to be. What curiosities do you have? Are there specific skills you'd like to hone? Which past projects resonated with you the most? From there, we began to identify the big-ticket items that needed to be accomplished over the semester, and found ways to plug in each team member's motivations and desires into the overall design of each project & initiative that we came up with. </p>
    </div>
    

    <h2>A Foundation of Trust </h2>

    <div class="py-4 clearfix">
        @include('pages.blogs.components.blog-image', [
            'src' => 'storage/post_images/treehouse-img2-campaign.png',
            'alt' => 'Campaign',
            'caption' => 'An excerpt of a student-produced campaign celebrating Greenhouse Studios\'s fifth birthday, created by Alyssa MacDonald (MFA \'22) and Lauren Harland (BA \'24)',
            'float' => 'right'
        ])
        <p class="mb-0">The most critical part of each agenda was the first bullet point: our "no B.S. check-in" (a ritual introduced by my colleague, Carly Wanner-Hyde - thanks Carly!). Each team member was invited to honestly answer the question, "How are you doing?" I feel that the key to doing this effectively, as both a staff member and (hopefully!) a mentor, was to offer my own response first, and to let myself be appropriately transparent and vulnerable. This was a group that truly trusted each other, and it showed in the freedom with which they brought their most brilliant ideas to the table. This team became an extremely tight-knit group, and our weekly meeting was easily the best part of my week! </p>
    </div>

    <h2>Teamwork Makes the Dream Work </h2>

    <div class="py-4 clearfix">
        @include('pages.blogs.components.blog-image', [
            'src' => 'storage/post_images/treehouse-img3-gsbrand.png',
            'alt' => 'Greenhouse Studios Brand',
            'caption' => 'An excerpt from a student-produced animation which illustrated the Greenhouse Studios design process model. Produced by Cameron Slocum, Cara Tracey, and Kenia Rodriguez. You can view the animation on our YouTube channel and our website.'
        ])
        <p class="mb-0">I know...[insert groan here]...but true-blue teamwork was the special sauce that made The Treehouse such a success each semester. As we identified specific projects and tasks that we were going to tackle–whether it be a social media campaign, an animation, or a blog post–students were given opportunities to act as project managers. The size and makeup of the team would depend on the scope of the project, but the majority of the teams were cross-disciplinary and given the freedom (and tools) to manage their own day-to-day strategies. Though I had an eye on each project and campaign, Treehouse collaborators were almost always the sole producers and creators, and they were given the latitude to show off 100% of their work in their own portfolios. </p>
    </div>

    <h2>How do students become a part of the team? </h2>

    <div class="py-4">
        <p class="mb-0">While weekly iteration of The Treehouse has been (at least temporarily) retired since the merge, that very same spirit is alive and well at Internal Insights & Innovation–if anything, the student-first ethos is even stronger. We take pride in the diversity of our students' backgrounds, as they join us from a wide variety of geographic, academic, and philosophical backgrounds. We consistently welcome new undergraduate employees through UConn’s 12twenty platform, and will announce these positions through our social media channels. However, if you or someone you know is interested in being a member of the team, please do feel free to reach out to us at any time! </p>
    </div>
    

<!-- Think for now lets keep style in the backgrounds/blogs.blade.php file so its universal -->
@endsection